name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1

#      - run: npm install
#      - run: npm run build

    
      - name: Checkout code
        uses: actions/checkout@v2
        
        
      - name: Set environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "VUE_APP_PATH=/gai" >> $GITHUB_ENV
          else
            echo "VUE_APP_PATH=/" >> $GITHUB_ENV
          fi

      # Use the environment variable in subsequent steps
      - name: Use environment variable
        run: |
          echo $VUE_APP_PATH

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VUE_APP_PATH: /gai/dist/
      - run: |
          ls
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr
          path: dist/
          remote_path: /home/projekterkea/www/gai
          remote_host: kea.dk
          remote_user: projekterkea
          remote_key: "${{ secrets.MARGPROJEKTERKEA }}"
      
